### ISSUE TITLE
License

### ISSUE THREAD

**Issue by theJenix** [elsassph/haxe-repl#3]
Do you have a license in mind and can you add it to the Github repo?  I stumbled across this and it looks like exactly what I need, but I'd like to see a license first.

Thanks!

**Comment by elsassph** [comment]
Hmm yeah forgot adding a license.

I usually go by a permissive ISC license, but do what you want with this code.

**Comment by theJenix** [comment]
Awesome, thanks!  When you get a free moment, could you add a license file to the repo (to satisfy legal on my end)?

**Comment by elsassph** [comment]
Done :)
